### ISSUE TITLE
Got "SERVER_ERROR engine error Timeout"  error while reading from an empty queue

### ISSUE THREAD

**Issue by icycrystal4** [weibocom/wqs#10]
### WQS Env
```
version: dev_beta   
commit: a819409e2c92832bf81946e0800b001d03a6910d 
```

### Expected behavior
On memcached protocol, an empty value with "END" sent to the client, when the 'key' is not found or expired.

```
get group1.test1
END
```

### Actual behavior
```
get group1.test1
SERVER_ERROR engine error Timeout
```

### Steps to reproduce the issue
1. make build-qservice
1. ./qservice -config ./config.properties
1. printf "get group1.test1\r\n" | nc localhost 11211

### Additional information you deem important
Timeout error is a look of confusion for biz clients, because timeout may happened out of limit of no messages.

**Comment by dup2X** [comment]
fixed by commit [https://github.com/weibocom/wqs/commit/b4a25656011f8a29b3b9da438838a5f461ad0965](url)
