### ISSUE TITLE
Add support for memcachd protocal

### ISSUE THREAD

**Issue by icycrystal4** [weibocom/wqs#4]
Memcached protocol is one of the most popular protocols on the internet, wqs will partially support the memcached text protocl, including "set", "get" command.
We can post a message over text memcached protocol:
```
set queuename 0 0 11\r\nhello world\r\n
```
also we can consume the message simply as following:
```
get queuename\r\n
```

**Comment by jackael9856** [comment]
the alpha release has supported memcached text protocol
